modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="distancemanagerfix"
version="${file.jarVersion}"
displayName="DistanceManager concurrency fix"
authors="TheDarkDnKTv"
description='''
This small fix mod resovles minecraft concurrency crash on server
'''
[[dependencies.distancemanagerfix]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.distancemanagerfix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="SERVER"